[tool.black]
line-length = 100

[tool.pyright]
typeCheckingMode = "basic"
exclude = ["**/external", "**/.pytest_cache"]
reportOptionalMemberAccess = false
reportOptionalSubscript = false

[tool.pytest.ini_options]
python_files = "test*.py"  # Instead of "test_*.py"