# -----------------------
# Installing / updating env
# -----------------------
# conda env update --file conda.yaml --prune
# conda activate dl_scratch
# pip install -r requirements.txt
# -----------------------
# NOTE: Using CUDA 12.1 due to same issue as:
#   https://github.com/pytorch/pytorch/issues/134929#issuecomment-2429992580
name: dl_scratch
channels:
  # See https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#conda-installation
  - nvidia/label/cuda-12.1.1
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - cuda
  - pip
  - python-graphviz  # Req. for pip graphviz (used w/ micrograd)
  - pip:
    - -r requirements.txt